### PR TITLE
internal(ci): Only run codeql when packages change

### PR DESCRIPTION
**Pull request by ntucker**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by ntucker** [comment]
@ljharb is "build Expected — Waiting for status to be reported " mean this is configure to require the action i just made only run sometimes?

**Comment by ljharb** [comment]
You renamed the action, and the "required" status is tied to the action name.

**Comment by ljharb** [comment]
`compressed-size-build` can't be required if conditional, so i can just uncheck "build"?

**Comment by ntucker** [comment]
I renamed it because I thought maybe the name confused someone - it should never have been required.

**Pull request merged**
