### PR TITLE
internal: publish

### PR DESCRIPTION
**Pull request by ntucker**
- @rest-hooks/core@1.0.2
 - @rest-hooks/endpoint@1.0.2
 - rest-hooks@5.0.2
 - @rest-hooks/rest@1.0.1

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
why bother updating the ones that don’t have any changes but deps?

**Comment by ntucker** [comment]
Then you ensure you get the latest version of their transitive dependencies.

**Comment by ljharb** [comment]
won’t that already happen when someone runs the update command, or reinstalls the base package? that’s kind of the whole point of semver ranges.

**Comment by ntucker** [comment]
- This is a lerna behavior, so you might ask the babel people to get their idea
- For me, running update is scary - I like to move things incrementally, and it's also easier to know that I can update something when the package I actually have installed changes. I wouldn't know to upgrade otherwise unless I did the scary `outdated` commands which show way too much stuff that I don't even understand half the time.

**Comment by ljharb** [comment]
Things like renovate and dependabot usually handle that kind of updating, but understood.

**Pull request merged**
