### PR TITLE
enhance: Remove FixtureManager in favor of MockResolver

### PR DESCRIPTION
**Pull request by ntucker**
### Motivation

#446 is the favored approach since it makes changing fixtures in a component easy

### Solution

Remove FixtureManager (use MockResolver instead)

### CODE REVIEW

**Comment by ntucker** [comment]
This is forked from the other branch so will rebase on merge

**Comment by ljharb** [comment]
This is labeled "enhance", but it seems like it's a breaking change?

**Comment by ntucker** [comment]
Breaking is marked by 'BREAKING CHANGE' in commit message. However - since the removed item was never released in a version (even beta), this actually breaks nothing.

**Comment by ljharb** [comment]
Ah, ok great, thanks for clarifying.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
